version: "3.8"

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - "${PORT:-4000}:4000"
    env_file:
      - .env
    volumes:
      - ./cube.js:/cube/conf/cube.js:ro
      - ./src:/cube/conf/src:ro
      - ./model:/cube/conf/model:ro
    depends_on:
      - cubestore

  cube_refresh_worker:
    image: cubejs/cube:latest
    env_file:
      - .env
    environment:
      CUBEJS_REFRESH_WORKER: "true"
    volumes:
      - ./cube.js:/cube/conf/cube.js:ro
      - ./src:/cube/conf/src:ro
      - ./model:/cube/conf/model:ro
    depends_on:
      - cubestore

  cubestore:
    image: cubejs/cubestore:latest
    ports:
      - "3030:3030"
