version: "3.8"

services:
  cube:
    build: .
    ports:
      - "${PORT:-4000}:4000"
    env_file:
      - .env
    environment:
      CUBEJS_CUBESTORE_HOST: cubestore
      CUBEJS_CUBESTORE_PORT: 3030
    depends_on:
      - cubestore

  cube_refresh_worker:
    build: .
    env_file:
      - .env
    environment:
      CUBEJS_REFRESH_WORKER: "true"
      CUBEJS_CUBESTORE_HOST: cubestore
      CUBEJS_CUBESTORE_PORT: 3030
    depends_on:
      - cubestore

  cubestore:
    image: cubejs/cubestore:latest
    ports:
      - "3030:3030"
